nohup: ignoring input
[2025-02-02 12:40:37 +0000] [58799] [INFO] Starting gunicorn 23.0.0
[2025-02-02 12:40:37 +0000] [58799] [INFO] Listening at: http://0.0.0.0:8000 (58799)
[2025-02-02 12:40:37 +0000] [58799] [INFO] Using worker: sync
[2025-02-02 12:40:37 +0000] [58846] [INFO] Booting worker with pid: 58846
[2025-02-02 12:40:37 +0000] [58847] [INFO] Booting worker with pid: 58847
[2025-02-02 12:40:37 +0000] [58848] [INFO] Booting worker with pid: 58848
[2025-02-02 12:40:38 +0000] [58846] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/app.py", line 2, in <module>
    from flaskr import create_app
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/flaskr/__init__.py", line 5, in <module>
    from flask_wtf.csrf import CSRFProtect
ModuleNotFoundError: No module named 'flask_wtf'
[2025-02-02 12:40:38 +0000] [58846] [INFO] Worker exiting (pid: 58846)
[2025-02-02 12:40:38 +0000] [58847] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/app.py", line 2, in <module>
    from flaskr import create_app
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/flaskr/__init__.py", line 5, in <module>
    from flask_wtf.csrf import CSRFProtect
ModuleNotFoundError: No module named 'flask_wtf'
[2025-02-02 12:40:38 +0000] [58847] [INFO] Worker exiting (pid: 58847)
[2025-02-02 12:40:38 +0000] [58848] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/labsstorage/home/ywaran842/htdocs/AI/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/app.py", line 2, in <module>
    from flaskr import create_app
  File "/var/labsstorage/home/ywaran842/htdocs/ota_ai/flaskr/__init__.py", line 5, in <module>
    from flask_wtf.csrf import CSRFProtect
ModuleNotFoundError: No module named 'flask_wtf'
[2025-02-02 12:40:38 +0000] [58848] [INFO] Worker exiting (pid: 58848)
[2025-02-02 12:40:38 +0000] [58799] [ERROR] Worker (pid:58847) exited with code 3
[2025-02-02 12:40:38 +0000] [58799] [ERROR] Worker (pid:58846) was sent SIGTERM!
[2025-02-02 12:40:38 +0000] [58799] [ERROR] Worker (pid:58848) was sent SIGTERM!
[2025-02-02 12:40:38 +0000] [58799] [ERROR] Shutting down: Master
[2025-02-02 12:40:38 +0000] [58799] [ERROR] Reason: Worker failed to boot.
